export const metadata = {
  title: 'Malaysia Fastest Live 4D Results Today (Keputusan 4D)',
  description: 'Check Magnum, Sports Toto, and Da Ma Cai 4D results instantly. No ads, no refreshing. Get live push notifications straight to your phone.',
};

export default function PromoPreLander() {
  return (
    <div className="min-h-screen bg-gray-50 font-sans text-gray-900">
      {/* Premium Header */}
      <header className="bg-red-700 text-white p-6 shadow-md sticky top-0 z-50">
        <div className="max-w-4xl mx-auto flex justify-between items-center">
          <div className="text-3xl font-black tracking-tighter flex items-center">
            NEO4D <span className="ml-2 bg-yellow-400 text-red-800 text-xs px-2 py-1 rounded font-bold uppercase">Live</span>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto bg-white min-h-screen p-8 shadow-2xl">
        <div className="text-center mb-10">
          <h1 className="text-4xl md:text-6xl font-black leading-tight mb-4 text-gray-900">
            Check 4D Results <span className="text-red-600">30 Seconds Faster</span> Than Everyone Else
          </h1>
          <p className="text-xl text-gray-600 font-medium max-w-2xl mx-auto">
            Tired of slow websites full of pop-up ads? NEO4D is the fastest Keputusan 4D platform in Malaysia and Singapore. 
          </p>
        </div>
        
        {/* Value Proposition Grid */}
        <div className="grid md:grid-cols-3 gap-6 mb-12">
          <div className="bg-red-50 p-6 rounded-2xl border border-red-100 text-center">
            <div className="text-4xl mb-4">⚡</div>
            <h3 className="font-bold text-lg mb-2">Ultra Fast</h3>
            <p className="text-gray-600 text-sm">Results update in real-time. No need to refresh the page constantly.</p>
          </div>
          <div className="bg-blue-50 p-6 rounded-2xl border border-blue-100 text-center">
            <div className="text-4xl mb-4">📱</div>
            <h3 className="font-bold text-lg mb-2">Ad-Free Mobile</h3>
            <p className="text-gray-600 text-sm">Clean, responsive design perfectly optimized for your smartphone.</p>
          </div>
          <div className="bg-yellow-50 p-6 rounded-2xl border border-yellow-100 text-center">
            <div className="text-4xl mb-4">🎯</div>
            <h3 className="font-bold text-lg mb-2">Lucky Predictions</h3>
            <p className="text-gray-600 text-sm">Get daily VIP "Tua Pek Kong" lucky numbers generated by our bot.</p>
          </div>
        </div>

        {/* Massive Call To Action */}
        <div className="bg-gray-900 rounded-3xl p-10 text-center shadow-2xl relative overflow-hidden border-4 border-amber-400">
          <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-red-500 via-yellow-500 to-red-500"></div>
          
          <div className="inline-block bg-red-600 text-white font-bold px-4 py-1 rounded-full text-sm mb-4 animate-pulse">
            VIP TELEGRAM BOT
          </div>
          
          <h2 className="text-3xl md:text-4xl font-black text-white mb-4">Get Instant Push Notifications!</h2>
          <p className="text-gray-300 mb-8 text-lg">
            Never miss a draw. Join the NEO4D Telegram Bot to receive a push notification the second the 7:00 PM draw begins, plus spin for daily lucky numbers!
          </p>
          
          <a 
            href="https://t.me/neo4d_bot/spinwheel" 
            className="inline-block w-full md:w-auto bg-gradient-to-r from-amber-400 to-amber-600 hover:from-amber-300 hover:to-amber-500 text-gray-900 font-black text-2xl py-5 px-10 rounded-full shadow-[0_0_30px_rgba(245,158,11,0.5)] transform transition hover:scale-105 active:scale-95"
          >
            👉 OPEN TELEGRAM BOT
          </a>
        </div>
      </main>
    </div>
  );
}
